//导航栏
var oProductNav = [
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9",
			price:2999,
			introduce:"新品"
		}
	]
]


//分类面板
var oCartProduct = [
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	],
	[
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		},
		{
			class:"cate-product-item",
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			msg:"小米9"
		}
	]
]



//选项卡产品
var oTabBox = [
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},	
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"热卖"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			areatop:{
				class:"product-area-top product-area-item",
				name:"小米净水器真的很棒，你可以用试试",
				st:1799,
				src:"images/ca.jpg"
			},
			areabottom:{
				class:"product-area-item product-area-bottom",
				name:"浏览更多",
				hot:"热门"
			}
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},	
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			areatop:{
				class:"product-area-top product-area-item",
				name:"小米净水器真的很棒，你可以用试试",
				st:1799,
				src:"images/ca.jpg"
			},
			areabottom:{
				class:"product-area-item product-area-bottom",
				name:"浏览更多",
				hot:"热门"
			}
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},	
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			areatop:{
				class:"product-area-top product-area-item",
				name:"小米净水器真的很棒，你可以用试试",
				st:1799,
				src:"images/ca.jpg"
			},
			areabottom:{
				class:"product-area-item product-area-bottom",
				name:"浏览更多",
				hot:"热门"
			}
		}
	],
	[
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			},
		},	
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			url:"https://www.baidu.com",
			src:"images/p1.jpg",
			name:"小米9 6GB +128G",
			des:"骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄",
			price:3699,
			del:4299,
			falg:{
				class:"off-flag",
				name:"减 800 元"
			},
			view:{
				class:"views",
				commen:"电视收到了,虽然有点晚,我感觉还不错，你觉得呢？",
				author:"评论来自于kuazhu"	
			}
		},
		{
			areatop:{
				class:"product-area-top product-area-item",
				name:"小米净水器真的很棒，你可以用试试",
				st:1799,
				src:"images/ca.jpg"
			},
			areabottom:{
				class:"product-area-item product-area-bottom",
				name:"浏览更多",
				hot:"热门"
			}
		}
	]
]